name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"        # change or add a matrix later

      - run: pip install -e .[dev]      # installs your package + dev extras
      - run: pytest -q                  # runs the test suite

